### ISSUE TITLE
OH MY GOD

### ISSUE THREAD

**Issue by SireTurret** [butmun/InterHippie2#12]
![image](https://user-images.githubusercontent.com/44091416/74586573-fc813a80-4ff9-11ea-860e-57c4be5c6b36.png)

YOU CAN'T RUN AROUND AS A GHOST OH GOD

**Comment by Muncher2112** [comment]
Is there any special way to reproduce this?  I don't have this issue


https://i.gyazo.com/8e6e0b18e4d61c05d63ff37fbd2fb31f.mp4

**Comment by SireTurret** [comment]
Try to succumb.

**Comment by Muncher2112** [comment]
I did, smacked myself with a sword until I could succumb

**Comment by Muncher2112** [comment]
Don't think this is happening, or more people would run into it during tests
