### ISSUE TITLE
port goonchat

### ISSUE THREAD

**Issue by SireTurret** [butmun/InterHippie2#16]
https://github.com/Baystation12/Baystation12/pull/28062

that travis compiler error is sure looking hefty but I'm sure we can do it

we can also look to CEV Eris code

**Comment by Muncher2112** [comment]
https://github.com/etet2/InterBay-Goonchat

**Comment by SireTurret** [comment]
Porting this smoking pile of shit of a chat would require effort out of my knowledge. Closed, but I'll keep this in mind for the distant future.
