### ISSUE TITLE
You can craft a crossbow frame but not a crossbow

### ISSUE THREAD

**Issue by Muncher2112** [butmun/InterHippie2#25]

**Comment by Muncher2112** [comment]
I've seen people do this using the old bay method, but would prefer it to become a real crafting recipe used in the menu.

**Comment by SireTurret** [comment]
Can be possible by just adding all the recipes to the crafting menu and making it step by step.

**Comment by mrpibb4201337** [comment]
i like the more indepth crafting :(

**Comment by SireTurret** [comment]
we keep it the old bay method because I hate humans
