### ISSUE TITLE
Many antag roles are broken, or not working in some fashion

### ISSUE THREAD

**Issue by Muncher2112** [butmun/InterHippie2#27]
#### Description of issue

Lots of antag roles don't work, but can still be spawned in secret.
We need to identify these, and disable them until they can be fixed

#### Difference between expected and actual behavior

You can only spawn as antag roles that work

#### Steps to reproduce 

Spawn as god cultist, or mercenary

**Comment by SireTurret** [comment]
God gamemode is probably working...but the problem is, it's so bad it feels like it doesn't work.

Mercenary not working is a mapping problem for some reason.

**Comment by Muncher2112** [comment]
Next thing I'm looking at for this is getting mercenary shuttle working, and making cult work.  Then we should (hopefully) have 4 antagonists working (traitor, changeling, mercenary, cult).  That'll be enough to close this issue, but new enhancements will be opened for modifying these 4 antags to work with interbay lore/technology level

**Comment by Muncher2112** [comment]
Traitor, changing, merc, and cult all work to some degree, but they should all be working in some capacity..   We can open up issues for their own specific issues.  Closing this.

**Comment by SireTurret** [comment]
Don't forget about raiders, they are pretty good.
