### ISSUE TITLE
You can't use lattice's or walls to move in space

### ISSUE THREAD

**Issue by Muncher2112** [butmun/InterHippie2#29]
#### Description of issue

You will just slide past lattice's and walls in space

#### Difference between expected and actual behavior

You should be able to grab on to them, and stop flying through space

#### Steps to reproduce 

Put on a suit and walk along the station

**Comment by SireTurret** [comment]
might be or might not be related to the movement changes

**Comment by SireTurret** [comment]
should work now maybe?
