### ISSUE TITLE
sillicons and pais can't ghost/succumb

### ISSUE THREAD

**Issue by danxnader** [butmun/InterHippie2#36]
ghosting as ai/borg/pai/mmi won't do anything

**Comment by Muncher2112** [comment]
Looking at baycode, they are doing the same things to AIs/pAIs.



https://github.com/butmun/InterHippie2/blob/b284156937687c94d87fd80b7373261fdee461c4/code/modules/mob/living/silicon/ai/ai.dm#L111
vs
https://github.com/butmun/InterHippie2/blob/b284156937687c94d87fd80b7373261fdee461c4/code/modules/mob/living/silicon/ai/ai.dm#L111

https://github.com/butmun/InterHippie2/blob/b284156937687c94d87fd80b7373261fdee461c4/code/modules/mob/living/silicon/pai/pai.dm#L94
vs
https://github.com/Baystation12/Baystation12/blob/7c177ecd7724147f427778702187ac011e087aa7/code/modules/mob/living/silicon/pai/pai.dm#L89

The question now is do we want to give them the ability?  Seems fine to me, especially with the instability in the codebase right now.

**Comment by SireTurret** [comment]
you're implying we'll ever use borgs

**Comment by SireTurret** [comment]
we don't have silicons
