### ISSUE TITLE
Nuke op base is overstocked

### ISSUE THREAD

**Issue by Muncher2112** [butmun/InterHippie2#53]
#### Description of issue

Nuclear operatives base has too much stuff in it (space suits, guns etc.) combined with them being to be able to buy stuff

Also, the base is generally disorganized and hard to intuitively understand.  Things like the first airlocks you see being out to nothing, etc.

#### Difference between expected and actual behavior

Base is streamlined, and only has enough spacesuits and possibly one extra sidearm per nuke op (5 at most)

#### Steps to reproduce 

Spawn as a nuke op

#### Specific information for locating

Frontier-5.dmm

**Comment by miner99213** [comment]
Done. They will be sorry they were born in this world as syndies now.

**Comment by miner99213** [comment]
I will rebuild it a bit later, as for now just nerfed them to oblivion.

**Comment by Muncher2112** [comment]
Closed, thanks miner99213

**Comment by danxnader** [comment]
what, he didnuffin. That was my pr

**Comment by Muncher2112** [comment]
Never mind, #106 is danxnader's PR.  Thanks danxnader

**Comment by miner99213** [comment]
Aye, my pr kinda broke game and I made whole syndie outpost so ruined that it looked more like space hobo's base, so danxnader did lighter but more game-friendly nerf. All credits to him.
