### ISSUE TITLE
Job selection screen is ugly

### ISSUE THREAD

**Issue by Muncher2112** [butmun/InterHippie2#8]
#### Description of issue

Job selection looks like shit:

![](https://i.gyazo.com/38342237750568019bb55cd54dc1ed9f.png)

#### Difference between expected and actual behavior

The old, color coded and nicely presented menu.  There are colors in the job datum's, so it should be "easy"

#### Steps to reproduce 

Latejoin

#### Length of time in which bug has been known to occur

I thought this worked, but I guess not.

**Comment by SireTurret** [comment]
should be easy to fix.

**Comment by Muncher2112** [comment]
![](https://i.gyazo.com/289205c9aad68ac8523e706128ec17b9.png)

**Comment by Muncher2112** [comment]
![](https://i.gyazo.com/2f2a626f4f5161e83e0249b3ccebad63.png)
