### ISSUE TITLE
There are annoying black borders around the UI 

### ISSUE THREAD

**Issue by SireTurret** [butmun/InterHippie2#83]
![image](https://user-images.githubusercontent.com/44091416/75887400-cc7bc900-5e3a-11ea-8dcc-a09be0e4168b.png)

**Comment by Muncher2112** [comment]
Resize your chat window, they should disapear

**Comment by Muncher2112** [comment]
No one else has complained about this so I *think* we can close it.  Will reopen if it happens to others
