### ISSUE TITLE
Getting up should be automatic

### ISSUE THREAD

**Issue by SireTurret** [butmun/InterHippie2#84]

**Comment by danxnader** [comment]
no, i want to see how newfags can't get up once we're on hub

**Comment by miner99213** [comment]
No. It will unneedingly simplify game. Newfags should learn the game hardway, it makes it more intresting and players more competent.

**Comment by miner99213** [comment]
Remember, game hates you. It makes life hard for you and achievieng even simplest goals more satisfying

**Comment by Muncher2112** [comment]
Agree with the last two points.  It's something we could revisit, but not needed right now
