### ISSUE TITLE
Decide on lobby music

### ISSUE THREAD

**Issue by Muncher2112** [butmun/InterHippie2#9]
Description of issue

Lobby music is unique
Difference between expected and actual behavior

Community should pick lobby music (Be careful of licenses)
Steps to reproduce

Listen to the music

**POST SUGGESTIONS HERE, THERE WILL BE A VOTE TO DECIDE ON WHICH TO PICK LATER**

**Comment by diegoxt45** [comment]
https://www.youtube.com/watch?v=iGuuOdD6iY4 hopefully EA doesn't sue us

**Comment by mrpibb4201337** [comment]
I'd say limit submissions to 3 per person so we have a good selection but not an assload 
https://www.youtube.com/watch?v=onCpEJDfyg0 
https://www.youtube.com/watch?v=b3LdMAqUMnM
https://www.youtube.com/watch?v=nZbW7EEry7M

**Comment by danxnader** [comment]
https://www.youtube.com/watch?v=I6m6idKEzgk

**Comment by Muncher2112** [comment]
https://www.youtube.com/watch?v=Rry_KUOVJjQ
https://www.youtube.com/watch?v=Q606Eg6ZcZ8
https://www.youtube.com/watch?v=Pq89iRCO4jQ

**Comment by KingTerrytheTerrible** [comment]
https://www.youtube.com/watch?v=3RGjvBrRRek

**Comment by Muncher2112** [comment]
https://cdn.discordapp.com/attachments/674908090604322817/678592342999040010/stahura.mp3
